name: Frequent Job

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute to start the job

jobs:
  frequent-job:
    runs-on: self-hosted

    steps:
      - name: Run task every 10 seconds
        run: echo "Hello, world! Running cron job on self-hosted runner"
